### ISSUE TITLE
Loading template tags requires database access

### ISSUE THREAD

**Issue by sttwister** [mixcloud/django-experiments#113]
Parsing templates that contain {% load experiments %} fails if no database access is available.

By looking at the code for 2 seconds, this is probably caused by importing the model manager in templatetags.experiments

Here is a possible use case where this causes problems:
- Compressing/minifying static assets during a pre-deployment phase on production where no database access is granted (i.e. heroku in some special cases) which requires template parsing

**Comment by jameschristopher** [comment]
Is there a known workaround for this issue (i.e. deploying on Heroku)?
