### ISSUE TITLE
EXPERIMENTS_AUTO_CREATE doesn't affect anything

### ISSUE THREAD

**Issue by volodymyrrudyj** [mixcloud/django-experiments#133]
Hi there. Looks like EXPERIMENTS_AUTO_CREATE doesn't affect anything and experiments are not being automatically created. Is it a known issue? Is there a quick workaround?

**Comment by sdcooke** [comment]
You're right...thanks for letting us know, we'll take a look

**Comment by sdcooke** [comment]
Hopefully we'll get https://github.com/mixcloud/django-experiments/pull/137 merged soon which should fix this.

**Comment by sdcooke** [comment]
This is now fixed in version 1.1.1 and uploaded to pypi
