### ISSUE TITLE
Minimum version specified is 1.7 but migration files are old

### ISSUE THREAD

**Issue by chhantyal** [mixcloud/django-experiments#139]
Migrations are still old, south scripts https://github.com/mixcloud/django-experiments/blob/master/experiments/migrations/0001_initial.py

How are you using it in production?

**Comment by sdcooke** [comment]
We don't use migrations in production so these fell behind. It looks like these have been fixed here https://github.com/mixcloud/django-experiments/pull/142 though, so I'll close this issue (the PR will be merged soon).
