### ISSUE TITLE
Hardcoded version of 'mock' and 'django-modeldict-yplan' breaks people's projects

### ISSUE THREAD

**Issue by spookylukey** [mixcloud/django-experiments#148]
requirements.txt has specific version of these libraries, instead of minimums. If a project needs a later version of e.g. mock, then installing django-experiments will downgrade mock and break the project. Libraries should never use specific versions for this reason.

**Comment by tysonclugg** [comment]
This will be fixed when a new release is made, since PR #159 was merged.
