### ISSUE TITLE
Found a bug in experiments.js

### ISSUE THREAD

**Issue by Vadim-Karpenko** [mixcloud/django-experiments#168]
$.post("/experiments/goal/" + goal_name);
need change to: 
` $.post("/experiments/goal/" + goal_name + '/');`

and please, write in README.rst to include this js file with static in template where need to use experiments.
Thanks for your great work, you make my job easier a lot.

**Comment by Kiryous** [comment]
+1

**Comment by PetrDlouhy** [comment]
This should be fixed in current master branch.
